### ISSUE TITLE
Wrong novel classification on character page

### ISSUE THREAD

**Issue by leroyvn** [regisphilibert/rougon#7]
Hi @regisphilibert, it seems that the novels associated to several character profiles are not correctly displayed. See, for instance, screenshots for Florent (Le Ventre de Paris) and Étienne Lantier (Germinal).

![Screenshot 2020-08-03 at 11 02 26](https://user-images.githubusercontent.com/34740232/89165488-ed2a8500-d578-11ea-9382-738a20890142.png)
![Screenshot 2020-08-03 at 11 02 42](https://user-images.githubusercontent.com/34740232/89165493-ef8cdf00-d578-11ea-87d0-cf0b495fb275.png)

**Comment by regisphilibert** [comment]
Thanks for catching that! I'll take a look!
